site_name: Anxiu's Note
site_url: https://anxiu0101.github.io
site_author: Anxiu
site_description: 安修(Anxiu)的笔记站
repo_name: Anxiu0101/note
repo_url: https://github.com/Anxiu0101/note
edit_uri: tree/master/docs
copyright: Copyright &copy; 2023 <a href="https://github.com/Anxiu0101" target="_blank" rel="noopener">Anxiu</a>

theme:
  name: material
  language: 'zh'
  icon:
    logo: material/notebook-outline
  custom_dir: overrides
  features:
  - content.code.annotate
  - content.code.copy
  - navigation.tracking
  - navigation.tabs
  - navigation.path
  - navigation.indexes
  - navigation.top
  - navigation.footer
  - search.share
  - search.suggest
  - toc.follow
  font: false
  palette:
    - scheme: default # 日间模式
      primary: deep
      accent: blue # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: Dark # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Light

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 3
      separator: "-"
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - footnotes
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra:
  annotation:
    json: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Anxiu0101
    - icon: fontawesome/solid/rss
      link: https://rss.anxiu.cloud
    - icon: fontawesome/solid/inbox
      link: mailto:anxiu.fyc@foxmail.com
  link:
    - icon: fontawesome/solid/home
      link: https://anxiu0101.github.io
#  analytics:
#    provider: custom
#    property: G-DYETCPM289

extra_css:
#  - stylesheets/childpage_card_grid.css
  - stylesheets/tasklist.css
  - stylesheets/custom.css
  - stylesheets/card.css
  - stylesheets/flink.css
  - stylesheets/changelog_extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
  - javascripts/mathjax.js

plugins:
  - rss
  - glightbox:
      width: 80%
  - statistics
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-]'
  - social
  - offline
  - tags
#  - info
  - git-revision-date-localized

nav:
- Home:
  - index.md
- Computer-Sci:
  - cs/index.md
# — 编程语言 —————————————————————————————————————————————————————
  - Program Lang:
    - Python:
      - Python Virtual Environment: cs/lang/py/Python-venv.md
    - Golang:
      - Interface in Go: cs/lang/go/interface-in-go.md
# — 算法原理 —————————————————————————————————————————————————————
  - Algorithm:
      - Raft distributed Algorithm: cs/algorithm/raft.md
- Web-Development:
    - web/index.md
# — 部署记录与一些开发工具的使用 —————————————————————————————————————
    - Deploy & Tools:
        - Config MySQL in Ubuntu: web/deploy/mysql-in-ubuntu.md
        - Nginx Introduction: web/deploy/nginx-intro.md
        - 在 Docker 中配置 PostgreSQL: web/deploy/postgre-in-docker.md
        - Docker Introduction: web/deploy/docker-intro.md
        - Dockerfile Introduction: web/deploy/dockerfile-intro.md
        - espanso simple use: web/deploy/espanso-intro.md
        - Systemctl Introduction: web/deploy/systemctl-intro.md
        - Config ssh in Win: web/deploy/win-ssh-config.md
# — 开发记录 ——————————————————————————————————————————————————————
    - Development:
        - Golang Optional Pattern: web/dev/Golang-optional-pattern.md
        - Compiler a Go Project: web/dev/go-project-compiler.md
        - Use tencent SMS in Go: web/dev/golang-tencent-SMS.md
        - Gorm struct label Guide: web/dev/gorm-struct-label.md
- Research:
  - rsc/index.md
  - Machine Learning:
    - rsc/ml/index.md
  - Security:
    - rsc/sec/index.md
- Others:
  - oth/index.md
#  - Resume:
#      - cv.pdf
# — 建站记录 ——————————————————————————————————————————————————————
  - Blog Build:
    - oth/blog/Markdown-Grammar.md
    - oth/blog/Build your personal MkDocs Site.md
